name: Python Build Workflow

# Triggers the workflow on push or pull request events on the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The OS for the runner (virtual machine)

    steps:
    - name: Checkout code  # Step 1: Check out the latest code from GitHub
      uses: actions/checkout@v2

    - name: Set up Python 3.8  # Step 2: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies  # Step 3: Install the dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run the Python program  # Step 4: Run the Python program
      run: python main.py

    - name: Save output to file  # Step 5: Save output to file
      run: echo "Hello from GitHub Actions!" > output.txt

    - name: Upload output file  # Step 6: Upload output file
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: output-file
        path: output.txt
